<!DOCTYPE html>
<html>
<head>
    <title>首页</title>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu-site-verification" content="XIBqsxRxKL"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <!-- Style-sheets -->
    <link href="/static/index/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
    <!--// Bootstrap-css -->
    <link href="/static/index/css/banner.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/static/index/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="/static/index/css/font-awesome.css" rel="stylesheet" type="text/css"media="all">
    <!-- Web-fonts -->
    <link href="http://fonts.googleapis.com/css?family=Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <!-- //Web-fonts -->
    {block name="css"}{/block}
</head>
<body>
{include file="header"}
{block name="nav"}
<!--// header-nav -->
<nav class="navbar navbar-inverse">
    <div class="collapse navbar-collapse js-navbar-collapse">
        <ul class="nav navbar-nav">
            <li class="dropdown mega-dropdown">
                <a href="/index/index/index.html">首页</a>
            </li>
            <li class="dropdown mega-dropdown">
                <a href="/index/index/blogtwo">软件开发 </a>
            </li>
            <li class="dropdown mega-dropdown">
                <a href="/index/index/blogthr">IT运维 </a>
            </li>
            <li class="dropdown mega-dropdown">
                <a href="#">需求中心</a>
            </li>
            <li class="dropdown mega-dropdown">
                <a href="/index/index/contact.html">联系我们 </a>
            </li>
        </ul>
    </div>
</nav>
{/block}
{block name="body"}{/block}
{include file="footer"}
