<footer id="footer" style="background-color: #0b0b0b">
    <div class="container">
        <div class="row" style="padding:50px 0px">
            <div class="col-md-4">
                <div class="mytab">
                    <div style="display: inline-block;"><img src="/static/index/images/f_wx.png" alt=""></div>
                    <div style="display: inline-block;color: #fff;transform: translateY(12%);;"><h3>微信联系：16620730233</h3></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mytab">
                    <div style="display: inline-block;"><img src="/static/index/images/f_wpr.png" alt=""></div>
                    <div style="display: inline-block;color: #fff;transform: translateY(12%);"><h3>QQ：231680528</h3></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mytab" >
                    <div style="display: inline-block;"><img src="/static/index/images/phoneIcon.png" alt=""></div>
                    <div style="display: inline-block;color: #fff;transform: translateY(12%);;"><h3>电话：16620730233</h3></div>
                </div>
            </div>
        </div>
        <div class="row">
            <p style="text-align: center;margin-top: 30px;color:#fff">@2020程兴服务时代科技有限公司版权所有　　京ICP备14034406号-2</p>
        </div>
    </div>
</footer>
<!-- banner -->
<script type="text/javascript" src="/static/index/js/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="/static/index/js/bootstrap.js"></script>
{block name="js"}{/block}
<script>
    $('.carousel').carousel({
        interval:3000
    })
</script>
</body>

</html>