<!-- 头部 -->
<!-- header-top -->
<div class="header_topw3layouts_bar">
    <div class="container">
        <div class="header_agileits_left">
            <ul>
                <li><i class="fa fa-phone" aria-hidden="true"></i> 0851-85750255</li>
                <li><i class="fa fa-envelope-o" aria-hidden="true"></i> <a href="mailto:info@example.com">gzcxfw@126.com</a></li>
            </ul>
        </div>
        <div class="clearfix"> </div>
    </div>
</div>
<!-- header-middle -->
<div class="header-middle">
    <div class="container">
        <div class="logof-w3-agile">
            <h1><a href="index.html">程兴服务</a></h1>
        </div>
        <div class="searchf-w3-agileits-headr">
            <form action="#" method="post">
                <input type="search" name="Search" placeholder="请你搜索公司服务" required="">
                <button type="submit" class="btn btn-default search" aria-label="Left Align">
                    <i class="fa fa-search" aria-hidden="true"> </i>
                </button>
            </form>
        </div>
        <div class="cart-mainf">
            <div class="educart educart2 cart cart box_1">
                <form action="#" method="post" class="last">
                    <input type="hidden" name="cmd" value="_cart">
                    <input type="hidden" name="display" value="1">
                </form>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!--// header-middle -->
