{extend name="base"}

{block name="body"}
<section class="carousel slide" id="shared_carousel" data-ride="carousel">
    <ol class="carousel-indicators">
        <li class="active" data-target="#shared_carousel" data-slide-to="0"></li>
        <li class="" data-target="#shared_carousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner banner3" role="listbox">
        <div class="item active">
            <img src="/static/index/images/banner1.jpg" alt="" class="img-responsive">
            <div class="">
                <span class="subject"></span>
            </div>
        </div>

        <div class="item">
            <img src="/static/index/images/banner3.jpg" alt="" class="img-responsive">
            <div class="">
                <span class="subject"></span>
            </div>
        </div>
    </div>
</section>
<!--	strength grWidth hiddentwo-->
<div class="services-agile-breadcrumb">
    <div class="inner_breadcrumb">
        <ul class="short_ls">
            <li>
                <a href="index.html">首页</a>
                <span>| |</span>
            </li>
            <li>首页</li>
        </ul>
    </div>
</div>
<div class="biaoti"><h1>About Us</h1></div>
<section style="border: 1px solid #fff" class="beiji">
    <div class="container ">
        <ul class="strengthMain row">
            <li class="col-md-6"><a><img src="/static/index/images/a1.jpg" alt="专业团队"><div class="font"><h3>专业团队</h3><p>面积1900平，成员300人，很可能是最大的一支网站信息建设服务团队</p></div></a></li>
            <li  class="col-md-6"><a><img src="/static/index/images/a2.jpg" alt="项目管理"><div class="font"><h3>项目管理</h3><p>项目式实施，确保创意与策略可靠落地</p></div></a></li>
        </ul>
        <ul class="strengthMain row">
            <li  class="col-md-6"><a><img src="/static/index/images/a3.jpg" alt="丰富经验"><div class="font"><h3>丰富经验</h3><p>12年行业经验，累计帮助超过千家企业建设了官方网站</p></div></a></li>
            <li  class="col-md-6"><a><img src="/static/index/images/a4.jpg" alt="技术支持"><div class="font"><h3>售后无忧</h3><p>7X24小时VIP服务专线，直通技术支持</p></div></a></li>
        </ul>
    </div>
</section>
<div id="kefu">
    <input type="checkbox" id="showKfList">
    <label for="showKfList" class="topBtn"></label>
    <span class="wechat">
		<em class="eweima">
			<img src="/static/index/images/微信图片_20200714152317.jpg" alt="datouwang.com">
		</em>
	</span>
    <span class="qq" title="点击进行咨询" onClick="window.open('http://wpa.qq.com/msgrd?v=3&uin=换成你自己的QQ号码&site=qq&menu=yes');"></span>
    <span class="other">
		<dl class="tel">
			<dt>13800138000</dt>
			<dd>7*24小时客服电话</dd>
		</dl>
	</span>
</div>
{/block}



