{extend name="base"}

{block name="body"}
<!-- banner -->
<div class="innerf-banner">
</div>
<!-- Page details -->
<div class="services-agile-breadcrumb">
    <div class="inner_breadcrumb">
        <ul class="short_ls">
            <li>
                <a href="index.html">首页</a>
                <span>| |</span>
            </li>
            <li>联系我们</li>
        </ul>
    </div>
</div>
<!-- //Page details -->
<!-- mail -->
<div class="mail">
    <div class="container">
        <h3 class="tittlef-agileits-w3layouts">联系我们</h3>
        <div class="shopf-sear-headinfo_mail_grids">
            <div class="col-md-7 contctf_mail_grid_right">
                <h3 class="sub-w3ls-headf">请填写此表格与我们联系。</h3>
                <form action="#" method="post">
                    <div class="inputf_left">
                        <input type="text" name="Name" placeholder="名称" required="">
                    </div>
                    <div class="inputf_right">
                        <input type="email" name="Email" placeholder="电子邮箱" required="">
                    </div>
                    <div class="clearfix"> </div>
                    <div class="inputf_left">
                        <input type="text" name="Telephone" placeholder="电话" required="">
                    </div>
                    <div class="inputf_right">
                        <input type="text" name="Subject" placeholder="业务" required="">
                    </div>
                    <div class="clearfix"> </div>
                    <div class="inputf">
                        <textarea name="Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Message...</textarea>
                    </div>
                    <input type="submit" value="提交">
                    <input type="reset" value="重置">
                </form>
            </div>
            <div class="col-md-5 contactf-left">
                <h3 class="sub-w3ls-headf">联络资料</h3>
                <div class="visit">
                    <div class="col-md-2 col-sm-2 col-xs-2 contact-icon-sidef">
                        <span class="fa fa-home" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-10 col-sm-10 col-xs-10 contact-text-shopf-sear-headinf0">
                        <h4>探望我们</h4>
                        <p>财富广场2号楼602</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="contactf-mail">
                    <div class="col-md-2 col-sm-2 col-xs-2 contact-icon-sidef">
                        <span class="fa fa-envelope" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-10 col-sm-10 col-xs-10 contact-text-shopf-sear-headinf0">
                        <h4>给我们发邮件</h4>
                        <p><a href="mailto:info@example.com">gzcxfw@126.com</a></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="call">
                    <div class="col-md-2 col-sm-2 col-xs-2 contact-icon-sidef">
                        <span class="fa fa-mobile" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-10 col-sm-10 col-xs-10 contact-text-shopf-sear-headinf0">
                        <h4>给我们打电话</h4>
                        <p>+18044261149</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="visit">
                    <div class="col-md-2 col-sm-2 col-xs-2 contact-icon-sidef">
                        <span class="fa fa-clock-o" aria-hidden="true"></span>
                    </div>
                    <div class="col-md-10 col-sm-10 col-xs-10 contact-text-shopf-sear-headinf0">
                        <h4>工作时间</h4>
                        <p>周一至周五09:00 AM-06:30 PM</p>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- Subscribe -->
<div class="wthree-subscribef-w3ls">
    <div class="container">
        <h3 class="tittlef-agileits-w3layouts white-clrf">注册我们的通讯</h3>
        <p class="white-clrf">直接在您的收件箱中接收我们的最新新闻</p>
        <div class="footer_w3layouts_gridf_right">
            <form action="#" method="post">
                <input type="email" name="Email" placeholder="电子邮箱地址" required="">
                <input type="submit" value="提交">
            </form>
        </div>
    </div>
</div>

<!--在线客服-->
<div id="kefu">
    <input type="checkbox" id="showKfList">
    <label for="showKfList" class="topBtn"></label>
    <span class="wechat">
		<em class="eweima">
			<img src="images/微信图片_20200714152317.jpg" alt="datouwang.com">
		</em>
	</span>
    <span class="qq" title="点击进行咨询" onClick="window.open('http://wpa.qq.com/msgrd?v=3&uin=换成你自己的QQ号码&site=qq&menu=yes');"></span>
    <span class="other">
		<dl class="tel">
			<dt>13800138000</dt>
			<dd>7*24小时客服电话</dd>
		</dl>
	</span>
</div>

{/block}



